- name: Replace the property value in the file
  lineinfile:
    dest: /home/confluent/confluent-7.3.1/etc/kafka/kraft/server1.properties
    regexp: '^log.dirs=.*$'
    line: "log.dirs=/home/confluent/kraft/logs"
    state: present
