- name: Copy file servers 1
  copy:
    remote_src: true
    src: /home/confluent/confluent-7.3.1/etc/schema-registry/schema-registry.properties
    dest: /home/confluent/confluent-7.3.1/etc/schema-registry/schema-registry1.properties
- name: Copy file servers 1
  copy:
    remote_src: true
    src: /home/confluent/confluent-7.3.1/etc/schema-registry/schema-registry.properties
    dest: /home/confluent/confluent-7.3.1/etc/schema-registry/schema-registry2.properties


