- name: A task that gets the status of the schema registries on the control node
  become: yes
  shell: systemctl status schemareg.service
  register: schema_registry_status

- name: Print the status of each schema reg instance
  debug:
    var: schema_registry_status.stdout
