- name: Create cluster id and get the value
  shell: /home/confluent/confluent-7.3.1/bin/kafka-storage random-uuid
  register: cluster_id
  when: inventory_hostname == 'uatgitmirr11'

- name: Print the cluster id
  debug:
    msg: "This is the cluster id {{ cluster_id }}"
# output clusterID: BfnTX9wnQgitegI8yjLSwg  


