- name: Replace the property value in the file
  lineinfile:
    dest: /home/confluent/confluent-7.3.1/etc/kafka/kraft/server1.properties
    regexp: '^node.id=.*$'
    line: "node.id=1"
    state: present  

- name: Replace the property value in the file
  lineinfile:
    dest: /home/confluent/confluent-7.3.1/etc/kafka/kraft/server2.properties
    regexp: '^node.id=.*$'
    line: "node.id=2"
    state: present

- name: Replace the property value in the file
  lineinfile:
    dest: /home/confluent/confluent-7.3.1/etc/kafka/kraft/server3.properties
    regexp: '^node.id=.*$'
    line: "node.id=3"
    state: present      
