- name: Get the topics of the Kafka Cluster
  shell: /home/confluent/confluent-7.3.1/bin/kafka-topics --bootstrap-server uatgitbrkr11:9092 --list
  register: topic_output

- name: Print the output of the topics
  debug:
    var: topic_output.stdout_lines


