# tasks file for common
- name: Include all tasks of the role common
  include_tasks: "{{ item }}"
  loop:
  #- copy-file-server.yml
  #- change-broker-id.yml
  #- controller-quorum-voters.yml
  #- create-cluster-id.yml
  #- change-log-dirs.yml
  #- format-storage-dir.yml
  #- create-service.yml
  #- reload-service.yml
  #- start-kafka-service.yml
  #- fetch-request-cert.yml
  - send-signed-certs.yml
  - status-kafka-service.yml
  
