- name: Start broker 1 in KRaft mode
  shell: /home/confluent/confluent-7.3.1/bin/kafka-server-start /home/confluent/confluent-7.3.1/etc/kafka/kraft/server1.properties  
  when: inventory_hostname == '20.86.65.24'
- name: Start broker 2 in KRaft mode
  shell: /home/confluent/confluent-7.3.1/bin/kafka-server-start /home/confluent/confluent-7.3.1/etc/kafka/kraft/server2.properties  
  when: inventory_hostname == '20.86.65.62'
- name: Start broker 3 in KRaft mode
  shell: /home/confluent/confluent-7.3.1/bin/kafka-server-start /home/confluent/confluent-7.3.1/etc/kafka/kraft/server3.properties
  when: inventory_hostname == '20.86.65.203'

