---
- name: A playbook to test if brokers are running on a remote machine
  hosts: kafka_broker
  tasks:
  - name: The task to check if its running
    command: systemctl status confluent-kafka
    register: broker_status
  - name: Display Broker Kafka status
    debug:
      var: broker_status.rc
    when: broker_status.rc == 0
    debug:
      msg: Broker is running
  - name: Report Broker is not running
    fail:
      msg: Broker is not running
    when: broker_status.rc != 0
     
