---
- name: A playbook to test if zookeeper is running on a remote machine
  hosts: zookeeper
  tasks:
  - name: The task to check if its running
    command: systemctl status confluent-zookeeper
    register: zookeeper_status
  - name: Display Zookeeper status
    debug:
      var: zookeeper_status.rc
    when: zookeeper_status.rc == 0
    debug:
      msg: Test
  - name: Report Zookeeper is not running
    fail:
      msg: Zookeeper is not running
    when: zookeeper_status.rc != 0
     
