---
- name: A task to see how debugging works in Ansible
  hosts: test_machines
  tasks: 
  - name: First task to execute a command on the remote machine and register it, what is it?
    file:
      path: ~/anstest 
      state: directory
  - name: Task that creates a file in the directory anstest
    file:
      path: ~/testerans.txt
      state: touch
