---
- name: Quicky checker to test if zookeeper and kafka_brokers are running
  hosts: zookeeper:kafka_broker
  tasks:
  - name: Check if zk is running
    shell: systemctl status confluent-zookeeper
    register: status_zookeeper
  - name: Print the zkpr status
    debug:
      msg: "This is the zkpr status {{ status_zookeeper.stdout }}"
#  - name: Print the broker status
#    shell: systemctl status confluent-server
#    register: server_status
#  - name: Show the status of the brokers
#    debug:
#      var: server_status
