- name: The playbook that tests the debug-test playbook
  hosts: test_machines
  tasks:
  - name: Check if a file has been created on a remote test machine
    stat:
      path: /home/confluent/testerans.txt
    register: testerans_status
  - name: Report file status
    debug:
      msg: "File exists"
    when: testerans_status.stat.exists
  - name: Report file failed status
    debug:
      msg: File does not exists
    when: not testerans_status.stat.exists    
      
#    stat:
#      path: /home/confluent/anstest.txt
#    register: file_info
#    debug: 
#      msg: file_info  
#- name: Check if file exists
  #  assert:
  #    that: file_info.stat.exists
  #  msg: "File does not exist"
