---
- name: Test the functionality of shell and check difference with command module
  hosts: test_machines
  tasks:
  - name: Try the shell application, DO SOMETHING
    shell: echo $SHELL
    register: shell_variable
  - name: Print it with debugging tools
    debug:
      var: shell_variable.stdout

