---
- name: A playbook that installs Kafka on the Zookeeper machines
  hosts: all
  tasks:
  - name: Check if brokers can be pinged
    ping:
  - name: Check if Java is installed, if not, install Java. 
    shell: java -version
    register: java_check
    ignore_errors: true
  - name: Output the version if installed
    debug:
      var: java_check
  - name: Output that Java is installed
    debug:
      msg: "Java version is installed {{ java_check }}"
    when: java_check == 0
  - name: Output that Java is not installed
    debug:
      msg: "Java is not installed {{ java_check }}"
    package: 
      name: openjdk-17-jdk
      state: present
    when: java_check != 0
  

  
    
    
    
  
