- name: A task that gets the status of the broker on the control node
  become: yes
  shell: systemctl status connect.service
  register: connect_status

- name: Print the kafka_status
  debug:
    var: connect_status.stdout
