- name: Install Confluent Comunnity Kafka
  command: curl -O https://packages.confluent.io/archive/7.3/confluent-community-7.3.1.tar.gz

- name: Unpack Confluent Kafka
  unarchive:
    remote_src: yes
    src:  /home/confluent/confluent-community-7.3.1.tar.gz
    dest: /home/confluent

- name: Remove unpacked Confluent Kafka
  file:
    path: /home/confluent/confluent-community-7.3.1.tar.gz
    state: absent
