# tasks file for common
- name: Include all tasks of the role common
  include_tasks: "{{ item }}"
  loop:
  - ping-common.yml
#  - check-java-install-common.yml
#  - find-install-path-java.yml
#  - send-latest-kafka.yml
#  - unpack-kafka.yml
#  - remove-unpacked-kafka.yml
#  - install-confluent.yml 
